### ISSUE TITLE
support PackageCompiler v2

### ISSUE THREAD

**Issue by oscardssmith** [JuliaLinearAlgebra/MKL.jl#101]
the changes are pretty minor, and I think this should be easy to support (ie it might just need someone to bump the compat bound).

**Comment by DilumAluthge** [comment]
cc: @ViralBShah

**Comment by DilumAluthge** [comment]
There is a guide for upgrading from v1 to v2: https://julialang.github.io/PackageCompiler.jl/stable/#Upgrading-from-PackageCompiler-1.0.

**Comment by ViralBShah** [comment]
Committed to master accidentally, but hopefully it's all good. dbd068f
