### ISSUE TITLE
Warn users about `*_NUM_THREADS` behavior in multithreaded Julia codes

### ISSUE THREAD

**Issue by carstenbauer** [JuliaLinearAlgebra/MKL.jl#106]
OpenBLAS and MKL [behave very much differently](https://discourse.julialang.org/t/matrix-multiplication-is-slower-when-multithreading-in-julia/56227/12?u=carstenbauer) when used in a multithreaded Julia process. Understandably, [this leads to confusions](https://discourse.julialang.org/t/regarding-the-multithreaded-performance-of-openblas/75450) for users. Given that `using MKL` is seen and also marketed as the easiest way to switch between OpenBLAS and MKL I think a warning in the README.md about the different behavior in a multithreaded settings is warranted.

Example:
The current MKL default for `BLAS.get_num_threads()` is # of cores, i.e. 40 on my machine. While this is good for serial Julia, it's pretty bad when you run your code with `julia -t N` in which case you will immediately oversubscribe your cores by a factor of `N`. This is not the case for OpenBLAS, which will still use 40 BLAS threads. However, there it is generally better to set `OPENBLAS_NUM_THREADS=1`.

**Comment by ViralBShah** [comment]
I suspect this all needs to go into the Julia manual's multi-threading section (even for notes related to MKL).

**Comment by carstenbauer** [comment]
Yeah, maybe. Definitely the OpenBLAS related things.

(BTW, I've written some compact notes down in the ThreadPinning.jl docs, see [here](https://carstenbauer.github.io/ThreadPinning.jl/dev/explanations/blas/))

**Comment by carstenbauer** [comment]
Closing in favor of https://github.com/JuliaLang/julia/issues/44201.
