### ISSUE TITLE
Warn about MKL being single threaded on Mac

### ISSUE THREAD

**Issue by KristofferC** [JuliaLinearAlgebra/MKL.jl#111]
After https://github.com/JuliaLinearAlgebra/MKL.jl/pull/99 MKL runs single-threaded on mac which is very bad for performance.
This will catch a lot of people off guard unless there is some screaming done by the package on load time that this is happening and saying how to re-enable it to how things used to be.

Personally, I still think this is not a good idea. The problem is with upstream and we should in my opinion not patch over it by wrecking performance.

**Comment by ViralBShah** [comment]
AppleAccelerate.jl now works on Mac (including Intel). It is also likely that the MKL bug is fixed in a recent release.

**Comment by ViralBShah** [comment]
I've disabled the single threading. The issues were in a very small part, and are upstream - and they are now documented in the README. Also, Intel Mac support is deprecated from 2024 onwards.
