### ISSUE TITLE
Issue with Julia nightly on Mac

### ISSUE THREAD

**Issue by cossio** [JuliaLinearAlgebra/MKL.jl#112]
I am having consistent CI failures on Mac, Julia nightly. See:

https://github.com/cossio/RestrictedBoltzmannMachines.jl/runs/6208852189

You can see all tests pass on other OS, and other versions of Julia. However, for Mac, Julia nightly, I get numerical values which are very wrong which makes some tests fail. The Julia code that is running is identical on all platforms.
Also this has been happening for a while now, the tests consistently fail on Mac Julia nightly only, at the same line of code, while tests pass on all other platforms (see https://github.com/cossio/RestrictedBoltzmannMachines.jl/commits/master).

I tracked the issue to MKL. Indeed, I was previously importing MKL before running CI. When I comment out the `import MKL` line, all tests pass (also on Mac, Julia nightly):

https://github.com/cossio/RestrictedBoltzmannMachines.jl/actions/runs/2240097071

(The only difference between those two commits, is the `import MKL` line has been commented out in the later).

Unfortunately I don't have Mac locally to try things, but perhaps someone else can reproduce this by just installing the RestrictedBoltzmannMachines.jl package (it's registered) and running tests. It's a worrying issue because I am getting wrong numerical values silently.

**Comment by cossio** [comment]
Possibly related: https://github.com/JuliaLang/julia/issues/40787, https://github.com/JuliaLang/julia/issues/43438, https://github.com/JuliaLinearAlgebra/MKL.jl/issues/98.

Though for me tests pass on Julia 1.7, it's just Julia nightly that fails, so I'm not sure if it's really the same issue.

**Comment by cossio** [comment]
Also, note that when I use MKL, I do `import MKL` before everything else..

**Comment by ViralBShah** [comment]
Seems to be fine on 1.8, but not good on 1.9 nightly. There's very little that is in our control here, with constrained CI machines, and an upstream developed MKL.
