### ISSUE TITLE
How to develop the library, the externally exposed interface is still OpenBlas

### ISSUE THREAD

**Issue by liushang0322** [JuliaLinearAlgebra/MKL.jl#113]
I am developing a self-use library but some of the internal functions I want to use MKL, but when I use MKL in the library, my julia bottom layer uses MKL directly, but what I want is to use mkl only in the library and externally It will not affect anything native to julia. Is there any solution?

**Comment by ViralBShah** [comment]
You really can have only one BLAS library for a given set of symbols. Well technically you could try to use a separate BLAS for ILP64 and LP64.
