### ISSUE TITLE
MKL Distributed slower！

### ISSUE THREAD

**Issue by 13299118606** [JuliaLinearAlgebra/MKL.jl#122]
I am using MKL to accelerate svd,
using MKL
svd will be 5-10 times faster
But it is far from enough in parallel:
Add the original svd 1.3s
using mkl will change to 0.15s

Then parallel each time 0.6s

If I declare in each process:
He will be slower than before without parallelism.
@everywhere using MKL
         From worker 2: 1.596812 seconds (24.28 k allocations: 128.745 MiB, 0.67% gc time)
       From worker 3: 1.621169 seconds (24.28 k allocations: 128.745 MiB, 0.38% gc time)
       From worker 4: 1.599108 seconds (24.28 k allocations: 128.745 MiB, 0.35% gc time)

**Comment by jishnub** [comment]
If you're initiating an `svd` on each process, you need to ensure that the cores aren't oversubscribed. In this case, it might be better to set `BLAS.set_num_threads(1)` or the equivalent in your case.
