### ISSUE TITLE
Eigen vectors of a hermitian matrix not orthogonal to each other in degenerate case

### ISSUE THREAD

**Issue by YemingMeng** [JuliaLinearAlgebra/MKL.jl#124]
## Issue Description

The results obtained from a MKL function `eigen` are inconsistent with those from the `LinearAlgebra` library. Using `LinearAlgebra` version of `eigen` results orthogonal eigen vectors, while the `MKL` version not.

## Reproduction Steps

1. Use Julia version 1.8.1 with the MKL library.

2. the following script gives non-zero result, which means columns of `values` are not orthogonal.

   ```julia
   using LinearAlgebra, MKL
   using JLD2
   
   @load "data.jld2" arrH
   H = Hermitian(arrH)
   _, values = eigen!(H)
   println(norm(values'*values - diagm(ones(size(H, 1)))))
   # 496.908116788313
   ```

 3. the following script gives zero result, which means orthogonal.

    ```julia
    using LinearAlgebra
    using JLD2
    
    @load "data.jld2" arrH
    H = Hermitian(arrH)
    _, values = eigen!(H)
    println(norm(values'*values - diagm(ones(size(H, 1)))))
    # 4.1385807732471933e-13
    ```

    
If eigenvectors are orthogonal to each other, all off-diagonal elements of `values'*values` should be zeros. When there exists degenerate eigenvalues, eigenvectors corresponding to these values will overlap, which means non-zeros at the corresponding off-diagonal position.
The data is stored in the "data.jld2" file, and it is loaded into the variable `arrH` using the `@load` function from the JLD2 library.

---
[data.zip](https://github.com/JuliaLinearAlgebra/MKL.jl/files/11584060/data.zip)

**Comment by ViralBShah** [comment]
This package only is an interface to MKL. I recommend trying the latest version, and if still an issue you will need to contact Intel's MKL team.
