### ISSUE TITLE
I need to install MKL manually before it becomes a dependency.

### ISSUE THREAD

**Issue by NoelAraujo** [JuliaLinearAlgebra/MKL.jl#125]
Hellos, 

I have my codes on github and I was expecting to run the following command without issues
```
import Pkg
Pkg.add(url="https://github.com/NoelAraujo/CoupledDipoles.jl")
```

I noticed that MKL.jl is the source of some problems, because somehow, it cannot be compiled (thus, my runtests fails on github actions)

_Sometimes_, the error is like this:
```
(...)
Building MKL → `/scratch/job.617411/input//.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/e01175ff53c062c52b6cbe441a4382e132f7c82e/build.log`
ERROR: LoadError: Error building `MKL`: 
 Downloading artifact: MKL
[ Info: Splicing in code to load MKL in /home/julia/bin/../share/julia/base/sysimg.jl
ERROR: LoadError: AssertionError: libblas_idx !== nothing && liblapack_idx !== nothing
Stacktrace:
 [1] replace_libblas(base_dir::String, name::String)
   @ Main /scratch/job.617411/input/.julia/packages/MKL/1aXoN/src/install.jl:10
 [2] change_blas_library(libblas::String)
   @ Main /scratch/job.617411/input/.julia/packages/MKL/1aXoN/src/install.jl:120
 [3] enable_mkl_startup()
   @ Main /scratch/job.617411/input/.julia/packages/MKL/1aXoN/src/install.jl:103
(...)
```
**However, here is the important part**: when I install MKL **first**, there is no error to install my codes
```
import Pkg
Pkg.add("MKL")
Pkg.add(url="https://github.com/NoelAraujo/CoupledDipoles.jl")
```

My best guess is that there is some racing condition with Julia multi-threading while compiling MKL.

Does anyone had a similar experience before?

**Comment by ViralBShah** [comment]
@KristofferC Any thoughts?

**Comment by prbzrg** [comment]
not having the latest version of MKL_jll as compat makes pkg downgrade MKL to a version without compat boundary (that is v0.3)

**Comment by prbzrg** [comment]
CompatHelper add it as updated in #142
