### ISSUE TITLE
Deprecation of 32-bit MKL in 2024.0 onwards.

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLinearAlgebra/MKL.jl#128]
MKL 2024.0 will stop shipping 32-bit MKL: https://www.intel.com/content/www/us/en/developer/articles/release-notes/onemkl-release-notes.html

**Comment by amontoison** [comment]
It's `oneMKL` and not `MKL` Viral.
`oneMKL` is for GPUs and it's what we use in `oneAPI.jl`.

**Comment by DilumAluthge** [comment]
Actually, hasn't MKL just been renamed to oneMKL?

**Comment by imciner2** [comment]
> Actually, hasn't MKL just been renamed to oneMKL?

This is my understanding. When you interact with Intel, the MKL product seems to always be refered to as "oneMKL" and the GPU offload things are just a small part of the stack.

And the main documentation page says (https://www.intel.com/content/www/us/en/docs/onemkl/developer-reference-c/2024-0/overview.html)

>  Intel® Math Kernel Library is now Intel® oneAPI Math Kernel Library (oneMKL). 

That said, I don't see the 32-bit deprecation notice in the release notes page right now, just the macOS removal notice. Has that page changed since the release to remove that notice?

**Comment by DilumAluthge** [comment]
Should we document this (the deprecation of 32-bit) in the MKL.jl README somewhere?

**Comment by imciner2** [comment]
Ok, I found the deprecation notice inside the 2023.2.0 release notes here https://www.intel.com/content/www/us/en/developer/articles/release-notes/onemkl-release-notes-2023.html

> As the industry has largely shifted to 64-bit architecture over the last decade, Intel® oneMKL 32-bit binaries will be deprecated in the upcoming Intel® oneMKL 2024.0 release and targeted to be removed after one year deprecation notice period. If you are currently using the 32-bit binaries, please consider upgrading to our 64-bit options. You can share your feedback or any concerns on the [oneMKL Community Forum](https://community.intel.com/t5/Intel-oneAPI-Math-Kernel-Library/Your-Feedback-Matters/td-p/1484337) or through [Priority Support.](https://www.intel.com/content/www/us/en/developer/get-help/priority-support.html)

It's a bit odd that the PGI support deprecation is announced in the 2023.2.0 release notes and repeated in the 2024.0.0 release notes, but that this 32-bit deprecation is not repeated.

**Comment by ViralBShah** [comment]
As @amontoison mentions - it deprecates 32 bit for oneMKL, which is for GPUs. We do not use that - we use MKL for CPUs. Hence nothing to document.

**Comment by imciner2** [comment]
I submitted a priority support request asking for clarification on this deprecation, and this is the response they gave:

> Ian, thank you for letting us know about your concern. We would like to inform you that, Intel® oneMKL 32-bit binaries are not yet deprecated (for windows and Linux). However, it will be discontinued in the future release and if you wish to download Intel® oneAPI Math Kernel Library ​(32-bit) kindly refer to the below link.
> 
> Link: https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit-download.html?operatingsystem=window&distributions=offline
> 
> Note: This package is an add-on that requires Intel® oneAPI Base Toolkit for Windows* (64 bit) to be installed first Intel® oneMKL 32-bit.
> 
> Feel free to let us know, if you have any further questions.

So they say they aren't yet deprecated apparently but will be discontinued in the future (but don't actually say when).
