### ISSUE TITLE
compat preventing upgrade to latest MLK_jll.jl

### ISSUE THREAD

**Issue by bclyons12** [JuliaLinearAlgebra/MKL.jl#143]
[MKL_jll](https://github.com/JuliaBinaryWrappers/MKL_jll.jl) released v2024.0.0+0 last week, but the compat statements in MKL.jl's Project.toml have `MKL_jll = "2022, 2023.2". Thus, when I updated my packages, MKL_jll was brought to the latest version and MKL was downgraded to v0.3.0.

**Comment by prbzrg** [comment]
It will be fixed by CompatHelper as updated in #142

**Comment by axsk** [comment]
Happened to me as well, and MKL 0.3.0 is not compiling on my system.
Workaround was to `]add MKL@0.6.1`
