### ISSUE TITLE
MKL 2024 dropped support for macOS

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLinearAlgebra/MKL.jl#146]
Intel macOS (`x86_64`):
- MKL 2023 and earlier support Intel macOS.
- MKL 2024 and later will not support Intel macOS.

Apple Silicon macOS:
- There has never been native support for MKL on Apple Silicon macOS. However, the MKL 2021 `x86_64` binaries will work on Apple Silicon if you run under Rosetta 2.
- MKL 2022 and later do not work under Rosetta 2.

**Comment by DilumAluthge** [comment]
We should probably mention this in the MKL.jl docs somewhere.

**Comment by DilumAluthge** [comment]
To give some more details:

Intel macOS (`x86_64`):
- MKL 2023 and earlier support Intel macOS.
- MKL 2024 and later will not support Intel macOS.

Apple Silicon macOS:
- There has never been native support for MKL on Apple Silicon macOS. However, the x86_64 MKL 2021 will work on Apple Silicon if you run under Rosetta 2.
- MKL 2022 and later do not work under Rosetta 2.

**Comment by imciner2** [comment]
> Isn't that oneMKL (and not MKL)?

The Anaconda channel providing MKL (https://anaconda.org/intel/mkl) doesn't contain anything for macOS for 2024.0.0, so it does affect the MKL we package in Yggdrasil (so we are unable to have macOS MKL_jll libraries for 2024.0.0).

This probably just needs to be noted in the readme to tell users on macOS to pin MKL_jll to 2023.2.0 to make it work. If we really want to, we could also add some code during init to do a check of the processor/OS/MKL_jll version and flag a problem if that is newer than 2023.2.0 on macOS x86_64.

**Comment by ViralBShah** [comment]
Yes, I think we need to do what @imciner2 mentioned.

**Comment by ViralBShah** [comment]
My understanding is that `MKL_jll` will only get installed if it is available through the artifacts system. I'll set up CI to test these cases.
