### ISSUE TITLE
MKL@0.6.2 build fails

### ISSUE THREAD

**Issue by valtunyan** [JuliaLinearAlgebra/MKL.jl#154]
I have a machine with multiple users and Julia is installed globally for all users, in directory `/opt`. Users don't have permission to edit anything in that directory and I get the following error during building `MKL.jl`

```
ERROR: Error building `MKL`:
 Downloading artifact: MKL
[ Info: Splicing in code to load MKL in /opt/julia-1.9.3/bin/../share/julia/base/sysimg.jl
ERROR: LoadError: SystemError: opening file "/opt/julia-1.9.3/bin/../share/julia/base/sysimg.jl": Permission denied
```

Is there any workaround, except downgrading MKL, or setting compatible version to `0.6.1` in my packages?

**Comment by imciner2** [comment]
Are you sure you are running an up-to-date 0.6.2? That looks like the old loading code before libblastrampoline was used to switch OpenBLAS for MKL. There is no code in MKL to go download separate artifacts and modify the sysimage anymore.

**Comment by valtunyan** [comment]
I'm sorry. I mixed up two different issues. You are right, my mentioned issue was from `0.3.0` version. My problem was that Julia's package manager downgraded `0.6.1` to `0.3.0` instead of upgrading. Issue was caused by another package's compatibility. Closing this issue.
