### ISSUE TITLE
Add benchmarks

### ISSUE THREAD

**Issue by aminya** [JuliaLinearAlgebra/MKL.jl#50]
Similar to IntelVectorMath, by using AcuteBenchmark, we can have a comprehensive benchmark.

https://github.com/aminya/AcuteBenchmark.jl
https://github.com/JuliaMath/IntelVectorMath.jl#performance

**Comment by ViralBShah** [comment]
Would be nice to have a comprehensive benchmarking suite.

**Comment by ViralBShah** [comment]
Closing since benchmarks should be separate packages. Good to have them!
