### ISSUE TITLE
Julia+MKL can't seem to multithread somehow

### ISSUE THREAD

**Issue by zsteve** [JuliaLinearAlgebra/MKL.jl#51]
Hi,
I installed and built Julia against MKL as per the README, and my code runs fine. However, originally with OpenBLAS I was able to get up to 16 local threads utilized, but with MKL I have so far been unable to make it use more than a single thread on the same code.

I have tried:
- BLAS.set_num_threads
- Setting the MKL_NUM_THREADS env variable

No luck so far. My Googling efforts also haven't found anything that helps. 

Any idea as to what could be the problem?

**Comment by ViralBShah** [comment]
Can you try again with the registered package?

**Comment by ViralBShah** [comment]
Please reopen if still a problem.
