### ISSUE TITLE
Docker ERROR: Unable to automatically install 'IntelOpenMP'

### ISSUE THREAD

**Issue by EliseJ** [JuliaLinearAlgebra/MKL.jl#61]
Hello, building MKL fails with the message below. After searching for answers I do install libcurl4 but this makes no difference. Docker file is below also.

`
#12 113.3     Cloning [56f22d72-fd6d-98f1-02f0-08ddc0907c33] Artifacts from https://github.com/JuliaPackaging/Artifacts.jl.git
  Installed Artifacts ─────── v1.3.0
#12 114.6 ERROR: Unable to automatically install 'IntelOpenMP' from '/opt/julia/packages/IntelOpenMP_jll/TUm6w/Artifacts.toml'
#12 115.6 Stacktrace:
#12 115.8  [1] error(::String) at ./error.jl:33
#12 116.2  [2] ensure_artifact_installed(::String, ::Dict{String,Any}, ::String; platform::Pkg.BinaryPlatforms.Platform, verbose::Bool, quiet_download::Bool) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Artifacts.jl:899
#12 116.3  [3] ensure_all_artifacts_installed(::String; platform::Pkg.BinaryPlatforms.Platform, pkg_uuid::Nothing, include_lazy::Bool, verbose::Bool, quiet_download::Bool) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Artifacts.jl:963
#12 116.3  [4] download_artifacts(::Pkg.Types.Context, ::Array{String,1}; platform::Pkg.BinaryPlatforms.Linux, verbose::Bool) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:663
#12 116.3  [5] download_artifacts(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}; platform::Pkg.BinaryPlatforms.Linux, verbose::Bool) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:642
#12 116.3  [6] add(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}, ::Array{Base.UUID,1}; preserve::Pkg.Types.PreserveLevel, platform::Pkg.BinaryPlatforms.Linux) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:1141
#12 116.3  [7] add(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}; preserve::Pkg.Types.PreserveLevel, platform::Pkg.BinaryPlatforms.Linux, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:188
#12 116.4  [8] add(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:139
#12 116.4  [9] #add#21 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:67 [inlined]
#12 116.4  [10] add at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:67 [inlined]
#12 116.4  [11] #add#20 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:66 [inlined]
#12 116.4  [12] add at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:66 [inlined]
#12 116.4  [13] add(::String; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:65
#12 116.4  [14] add(::String) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:65
#12 116.4  [15] top-level scope at none:1
executor failed running [/bin/sh -c julia -e 'using Pkg; Pkg.add("MKL"); Pkg.build("MKL")']: exit code: 1
`

`julia> versioninfo()
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, haswell)
Environment:
  JULIA_DEPOT_PATH = /opt/julia
  JULIA_PKGDIR = /opt/julia
  JULIA_VERSION = 1.5.3`

Dockerfile used

`FROM ubuntu:18.04
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libatomic1 \
    openssh-client \
    python \
    gfortran \
    gcc \
    libcurl4 \
    perl \
    wget \
    m4 \
    cmake \
    pkg-config \
    git \
    && apt-get clean && rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*

ENV JULIA_DEPOT_PATH=/opt/julia
ENV JULIA_PKGDIR=/opt/julia
ENV JULIA_VERSION=1.5.3

ENV BINARYPROVIDER_DOWNLOAD_ENGINE=wget

RUN mkdir /opt/julia-${JULIA_VERSION}
RUN cd /tmp
RUN wget --no-check-certificate https://julialang-s3.julialang.org/bin/linux/x64/1.5/julia-${JULIA_VERSION}-linux-x86_64.tar.gz
RUN tar xzf julia-${JULIA_VERSION}-linux-x86_64.tar.gz -C /opt/julia-${JULIA_VERSION} --strip-components=1
RUN rm -rf /tmp/julia-${JULIA_VERSION}-linux-x86_64.tar.gz
RUN ln -fs /opt/julia-*/bin/julia /usr/local/bin/julia

RUN julia -e 'using Pkg; Pkg.add("MKL"); Pkg.build("MKL")'`

**Comment by ViralBShah** [comment]
This has to do with other packages and downloading, not MKL.jl. Hopefully it is fixed.

**Comment by giordano** [comment]
I can reproduce the issue with the provided Dockerfile, but not sure what's going on

**Comment by ViralBShah** [comment]
Hopefully the revamped Downloads.jl stuff in 1.6 just works?

**Comment by giordano** [comment]
It's a security certificate issue:
```
root@cd2c24cec8d7:/# julia 
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.3 (2020-11-09)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.5) pkg> add MKL_jll
   Updating registry at `/opt/julia/registries/General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Resolving package versions...
Downloading artifact: IntelOpenMP
--2021-02-28 18:08:12--  https://pkg.julialang.org/artifact/947793e42b663bacd09f00d96aa96a47095f3b1c
Resolving pkg.julialang.org (pkg.julialang.org)... 199.232.58.217, 2a04:4e42:4b::729
Connecting to pkg.julialang.org (pkg.julialang.org)|199.232.58.217|:443... connected.
ERROR: cannot verify pkg.julialang.org's certificate, issued by 'CN=GlobalSign Atlas R3 DV TLS CA 2020,O=GlobalSign nv-sa,C=BE':
  Unable to locally verify the issuer's authority.
Downloading artifact: IntelOpenMP
--2021-02-28 18:08:12--  https://github.com/JuliaBinaryWrappers/IntelOpenMP_jll.jl/releases/download/IntelOpenMP-v2018.0.3+2/IntelOpenMP.v2018.0.3.x86_64-linux-gnu.tar.gz
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
ERROR: cannot verify github.com's certificate, issued by 'CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US':
  Unable to locally verify the issuer's authority.
ERROR: Unable to automatically install 'IntelOpenMP' from '/opt/julia/packages/IntelOpenMP_jll/TUm6w/Artifacts.toml'
```

**Comment by giordano** [comment]
@EliseJ you need to install also the package `ca-certificates` with `apt-get install`.  With that, installation is successful for me
