### ISSUE TITLE
Libblastrampoline: less verbose version of get_config()

### ISSUE THREAD

**Issue by crstnbr** [JuliaLinearAlgebra/MKL.jl#73]
Currently we tell users with >= Julia 1.7, i.e. using the new libblastrampoline facilities, to check `BLAS.get_config()` to see whether they are using OpenBLAS or MKL. However, the output of `BLAS.get_config()` is rather verbose and contains lots of information that is likely irrelevant for the regular user.

```Julia
LinearAlgebra.BLAS.LBTConfig(LinearAlgebra.BLAS.LBTLibraryInfo[
LinearAlgebra.BLAS.LBTLibraryInfo("/Users/viral/.julia/artifacts/
073ff95e2c63501547247d6e1321bf4ee2a78933/lib/libmkl_rt.1.dylib", Ptr{Nothing} 
@0x00007fb6a5ef4820, "", UInt8[0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 
0xff, 0xff  …  0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01], 
:ilp64, :plain)], [:f2c_capable], ["LAPACKE_c_nancheck", "LAPACKE_cbbcsd", 
"LAPACKE_cbbcsd_work", "LAPACKE_cbdsqr", "LAPACKE_cbdsqr_work", 
"LAPACKE_cgb_nancheck", "LAPACKE_cgb_trans", "LAPACKE_cgbbrd", 
"LAPACKE_cgbbrd_work", "LAPACKE_cgbcon"  …  "zunmlq_", "zunmql_", "zunmqr_", 
"zunmr2_", "zunmr3_", "zunmrq_", "zunmrz_", "zunmtr_", "zupgtr_", "zupmtr_"])
```

I propose that we add a simpler version of this function that either just returns the filename of the BLAS library, i.e. `libmkl_rt.1.dylib` in the case above, or checks for `mkl` or `openblas` substrings in this filename and just returns `:mkl` or `:openblas64`, i.e. what `BLAS.vendor()` was doing up until 1.7. The latter would be my preference.

Do we need a new function name for this or can we refactor the old `BLAS.vendor()` for this? Maybe that's not possible but I find it rather confusing that it outputs `:openblas64` despite that fact that `libmkl_rt.1.dylib` is used.

I'll prepare a PR once we've agreed on something here.

ping: @ViralBShah

**Comment by ViralBShah** [comment]
The old `BLAS.vendor()` needs to be deprecated. It is just there so that it does not break package code that depends upon its presence. See the comments in the code.

I think what we need is a better display method for the `LBTConfig` datatype, rather than a new method. 

cc @staticfloat for what is needed in such a PR.

**Comment by ViralBShah** [comment]
I think this issue may be best filed in the Julia repo.

**Comment by crstnbr** [comment]
Will make a PR over at the Julia repo. How do you like this?

```Julia
julia> BLAS.get_config()
LinearAlgebra.BLAS.LBTConfig
Libraries:
└ libopenblas64_.dylib

julia> using MKL
[ Info: Precompiling MKL [33e6dc65-8f57-5167-99aa-e5a354878fb2]

julia> BLAS.get_config()
LinearAlgebra.BLAS.LBTConfig
Libraries:
└ libmkl_rt.1.dylib

julia> BLAS.get_config().loaded_libs[1]
LinearAlgebra.BLAS.LBTLibraryInfo
├ Library: libmkl_rt.1.dylib
├ Interface: ilp64
└ F2C: plain
```

**Comment by crstnbr** [comment]
Let's move the discussion to https://github.com/JuliaLang/julia/pull/40357.
