### ISSUE TITLE
Is MKL.jl working with windows 10?

### ISSUE THREAD

**Issue by jlperla** [JuliaLinearAlgebra/MKL.jl#80]
Should the latest released version be s working on windows 10 and Julia 1.6.1?  I tried to follow the instructions.  i.e. in a terminal with the global environment activated
```
] add MKL
```
No errors shown at all.  Then for good measure after a restart
```
(@v1.6) pkg> build MKL
    Building MKL → `C:\Users\jesse\.julia\scratchspaces\44cfe95a-1eb2-52ea-b672-e2afdf69b78f\52c39a2b156743873c3919cd8ce83ac6075cc45f\build.log`
```
And no errors at all... though that log file is empty, if it is supposed to have something iin it.

But after I restart julia and open a terminal:
```julia
julia> using LinearAlgebra
julia> BLAS.vendor()
:openblas64
```
So it doesn't look like it worked... Any ideas?  Did I miss anything obvious?  I also tried `using LinearAlgebra, MKL; BLAS.vendor)`  which I didn't think was necessary but shows the same result.

**Comment by BenjaminBorn** [comment]
I just did the same under MacOS and have the same issue.

**Comment by WorldsOkayestAirman** [comment]
I'm confirming the same issue on Linux as well.

**Comment by mihalybaci** [comment]
I think the fix just hasn't been tagged in a release yet. I got the same null result just `add`ing MKL, but when I did `add MKL#master` it seems to have built properly according to `BLAS.vendor()`.

**Comment by ViralBShah** [comment]
Can you try it out with Julia 1.7 RCs?
