### ISSUE TITLE
MKL and PyPlot crash

### ISSUE THREAD

**Issue by PaulSoderlind** [JuliaLinearAlgebra/MKL.jl#89]
MWE (on Windows 10 64bit, Julia  1.7.0-rc1, Python 3.8, matplotlib 3.4.2)
```
using MKL
using PyPlot
```
gives an error message that starts with
`Exception: EXCEPTION_ACCESS_VIOLATION at 0x7ffc66b5a25c -- mkl_blas_avx2_xsdot`

Instead, by loading PyPlot first and MKL second, then I can plot.

Did I miss something?

**Comment by ViralBShah** [comment]
Dup of #97
