### ISSUE TITLE
Having installed MKL interferes with julia build process

### ISSUE THREAD

**Issue by gwd999** [JuliaLinearAlgebra/MKL.jl#92]
After having MKL installation in julia 1.6.3, which I build via `make` off the `v1.6.3` tag, break VS Code julia-extension languageserver functionality I attempted to do a fresh julia build again from source;    
so I did a `git fetch` to bring me up-to-date again and `git checkout v1.7.0-rc1` to investigate how `MKL.jl` behaves with VSC and `julia-v1.7.0-rc1` BUT running ` make`  then ends with  
```
error during bootstrap:
LoadError("sysimg.jl", 19, ArgumentError("Package MKL not found in current path:\n- Run `import Pkg; Pkg.add(\"MKL\")` to install the MKL package.\n"))
require at ./loading.jl:967
``` 
`make` after `make clean` or `make cleanall` will end with the same error
 
Quite "disturbing" - some documentation on how to do a clean sweep of `MKL`, such that it does not produce these types of imo unexpected interferences with  the julia build process would be helpful.    

The only way I was able to build `v1.7.0-rc1` was by deleting `rm -rf julia` the whole folder and doing another `git clone ...` of the julia repo and then executing `make`

**Comment by ViralBShah** [comment]
Dup of #58 

Basically, on Julia 1.6, we rebuild the sysimage with MKL, which leads to all these issues. 1.7 does not have this issue since it uses LBT.
