### ISSUE TITLE
Make precompile statements an artifact?

### ISSUE THREAD

**Issue by Roger-luo** [JuliaLinearAlgebra/MKL.jl#93]
Currently this package downloads the precompile script from Julia GitHub repo via as raw GitHub content which seems to be blocked by GFW in China 

https://github.com/JuliaLinearAlgebra/MKL.jl/blob/d4e61086c4c5f2d6606bb7e0b72cd9cf33ea6068/src/install.jl#L94

As a result we won't be able to mirror this file via the pkg server and pkg storage service so we recently heard some complains on Chinese chat group about this. I'm wondering if we could make it as an artifact or maybe the precompile script can be shipped with Julia itself?

**Comment by Roger-luo** [comment]
Ok maybe should update the README.md or leave a note somewhere?

**Comment by ViralBShah** [comment]
The README already notes the differences between 1.6 and 1.7, but please do submit a PR if something can be further clarified.
