### ISSUE TITLE
Building fails with dev version of PackageCompiler: sysimage_path not set

### ISSUE THREAD

**Issue by ikirill** [JuliaLinearAlgebra/MKL.jl#95]
At some point PackageCompiler.jl stopped replacing the base julia sysimage by default and now requires a sysimage_path to be passed:
https://github.com/JuliaLang/PackageCompiler.jl/blob/510879875254c2fcf784e46d1b46dfcd7d955fbe/src/PackageCompiler.jl#L405 See commit https://github.com/JuliaLang/PackageCompiler.jl/commit/e4716cca918eea77b9703465892911b09b2edd2b

The install script https://github.com/JuliaLinearAlgebra/MKL.jl/blob/238a4bb8d65037657d1e697f14655834249f309d/src/install.jl#L132 uses the old interface.

I made it work with the following change:
```
    @eval begin
        using PackageCompiler
        sysimage_path = joinpath(dirname(PackageCompiler.current_process_sysimage_path()), "mkl_sysimage.so")
        PackageCompiler.create_sysimage(; incremental=false,
                                        sysimage_path=sysimage_path,
                                        script=get_precompile_statments_file())
        @info "Wrote MKL system image at $sysimage_path"
    end
```
but this isn't ideal because it writes to a directory the user might not have write permissions for, and the info message is suppressed in Pkg's output by default, it only appears in logs.

**Comment by ViralBShah** [comment]
Right on macOS, it doesn't like it if you overwrite the default binaries. Maybe just make the default the user's home directory?

**Comment by KristofferC** [comment]
Imo this commit is faulty https://github.com/JuliaLinearAlgebra/MKL.jl/commit/dbd068fb495552111b4fb7b953700c917e102117. MKL.jl does not work with PackageCompiler 2.0.

**Comment by ViralBShah** [comment]
I wonder if we can just bump MKL.jl to have a Julia 1.7 minimum dependency, remove PackageCompiler, and people on 1.6 can just use an older version of MKL.jl. We almost don't expect anything to change in the older versions. 

In fact, very soon, we will want LBT 5.0 and Julia 1.8 as the minimum.

**Comment by KristofferC** [comment]
> I wonder if we can just bump MKL.jl to have a Julia 1.7 minimum dependency, remove PackageCompiler, and people on 1.6 can just use an older version of MKL.jl. We almost don't expect anything to change in the older versions.

Yes, this will work well.

**Comment by danielwe** [comment]
So 1.6 users should pin to version 0.4.3. Perhaps this should be added to the readme?

**Comment by ViralBShah** [comment]
@giordano @KristofferC Is it possible to unregister 0.4.4 from the registry, so that people on MKL with Julia 1.6 always have a working version?

Alternatively, I just released v0.5 which is 1.7 only, but is it possible to make a new 0.4.5 release that works on 1.6 (basically downgrade PackageCompiler)?

**Comment by giordano** [comment]
> Is it possible to unregister 0.4.4 from the registry, so that people on MKL with Julia 1.6 always have a working version?

You can yank a version in the registry by adding the line
```
yanked = true
```
See for example https://github.com/JuliaRegistries/General/issues?q=label%3Ayank+sort%3Aupdated-desc+is%3Aclosed

**Comment by ViralBShah** [comment]
Thanks. Submitted https://github.com/JuliaRegistries/General/pull/55490
