### ISSUE TITLE
Disable use of multi-threaded MKL on mac

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLinearAlgebra/MKL.jl#98]
Based on the discussions in 

https://github.com/JuliaLang/julia/issues/40787
https://github.com/JuliaLang/julia/issues/43438

It seems the simplest thing may be to not allow multi-threaded MKL on the mac. What would be the easiest way to achieve this?

**Comment by ViralBShah** [comment]
I wonder if THREADING_GNU will help address this. 

https://github.com/JuliaLinearAlgebra/MKL.jl/blob/238a4bb8d65037657d1e697f14655834249f309d/src/MKL.jl#L18

**Comment by pablosanjose** [comment]
Disabling multithreading in MKL kills most of the benefit of the package respect OpenBLAS. I don't think that's a good approach. #40787 is only an issue if one uses SpecialFunctions. Not sure about #43438, but wouldn't it be better to try to understand where the bug in threading is instead of simply disabling it? (Apologies if I misunderstood the issue here)

**Comment by ViralBShah** [comment]
It is not just SpecialFunctions. It is possibly triggered through any fortran library. The bug is not in Julia's threading - it is that Intel OpenMP that MKL uses is incompatible with gcc libgomp (loaded by almost any fortran library). On linux, Intel provides a version that will use libgomp - but not on mac.

Can you try the TBB option to see if that works reliably and also can use threads?

**Comment by ViralBShah** [comment]
See #43438 for another potential case that does not use SpecialFunctions.

**Comment by pablosanjose** [comment]
No luck:

**Comment by ViralBShah** [comment]
A better solution is what is discussed in https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/700

**Comment by ViralBShah** [comment]
Note added to: https://github.com/JuliaLinearAlgebra/MKL.jl/blob/master/README.md#usage

**Comment by ViralBShah** [comment]
We may have to disable MKL multi-threading on mac - it is quite problematic:

https://github.com/JuliaLinearAlgebra/MKL.jl/pull/104#issuecomment-1057514744

**Comment by pablosanjose** [comment]
Perhaps, since the future of Macs seems to be decoupled from Intel hardware, disabling multithreading in MKL on mac may not be such an issue going forward (correctness always comes before performance). But it does place a higher priority to get the Accelerate API to work with LBT. My 2c.

**Comment by ViralBShah** [comment]
The Accelerate API already works with LBT. The missing piece is LAPACK (since Apple ships a 10 year old LAPACK and we use some of the nice new capabilities like `dgesdd` etc.). Good news is this is not too difficult - needs addressing  https://github.com/JuliaPackaging/Yggdrasil/issues/2657 and then some integration and testing since this is the first time we'll have a separate BLAS and LAPACK.

**Comment by ViralBShah** [comment]
I have seen too many issues with MKL on mac - that I don't feel it is right to give people something that is highly likely to give the wrong answer. I'm going to make single threaded the default here and people can always change that through the API to enable threading.
